### ISSUE TITLE
Bug Fixed：Don't show image

### ISSUE THREAD

**Issue by actforjason** [syuchan1005/ImageComment#2]
https://github.com/syuchan1005/ImageComment/blob/68ed59051e3e669c77397a609047811f27ce5d9c/src/main/java/com/github/syuchan1005/imagecomment/CommentUtil.java#L128

change to 
```Java
return ((JBHiDPIScaledImage) thumbnail).getDelegate();
```

**Comment by syuchan1005** [comment]
Thanks for the report. I have released a new version today, 1.0.3, and you can update from your IDE in 2-3 days.
If you have the same problem with this version, could you please reopen this issue with the details?

**Comment by actforjason** [comment]
Thanks for your update! I wonder if there is a way to keep the resolution of the popup image while zooming. The following method results in a large loss of image resolution：
https://github.com/syuchan1005/ImageComment/blob/7ee066b91236a2841e089e7bbb8b3b7c9073279d/src/main/java/com/github/syuchan1005/imagecomment/MouseHoverHandler.java#L371-L374
original image：
![image](https://user-images.githubusercontent.com/57058325/167255054-aab815c0-f983-4aa5-894a-a1afdf711a39.png)
popup image：
![image](https://user-images.githubusercontent.com/57058325/167255170-cbd694e4-9dec-4f57-a0e2-b50ce6e68b5a.png)
